// backend/src/modules/auth/permissions.js
// Single source of truth for permission policy.
//
// Policy principle:
// OWNER controls the tenant.
// MANAGER helps run operations.
// Staff roles only access the work needed for their job.
//
// Do not give MANAGER owner-grade powers such as:
// - editing store settings
// - creating/editing/deactivating members
// - resetting passwords
// - managing branches
// - billing control
// - full audit control

const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Settings
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_EDIT_GENERAL: "SETTINGS_EDIT_GENERAL",
  SETTINGS_VIEW_ROLES: "SETTINGS_VIEW_ROLES",

  // Branches
  BRANCHES_VIEW: "BRANCHES_VIEW",
  BRANCHES_CREATE: "BRANCHES_CREATE",
  BRANCHES_EDIT: "BRANCHES_EDIT",
  BRANCHES_ARCHIVE: "BRANCHES_ARCHIVE",

  // Members / staff
  MEMBERS_VIEW: "MEMBERS_VIEW",
  MEMBERS_CREATE: "MEMBERS_CREATE",
  MEMBERS_EDIT: "MEMBERS_EDIT",
  MEMBERS_DEACTIVATE: "MEMBERS_DEACTIVATE",
  MEMBERS_RESET_PASSWORD: "MEMBERS_RESET_PASSWORD",

  // Audit / billing
  AUDIT_VIEW: "AUDIT_VIEW",
  BILLING_VIEW: "BILLING_VIEW",

  // POS
  POS_VIEW: "POS_VIEW",
  POS_CREATE_SALE: "POS_CREATE_SALE",
  POS_VIEW_SALES: "POS_VIEW_SALES",
  POS_VIEW_CREDIT: "POS_VIEW_CREDIT",
  SALE_PAYMENT_ADD: "SALE_PAYMENT_ADD",
  SALE_CANCEL: "SALE_CANCEL",
  SALE_REFUND: "SALE_REFUND",
  WARRANTY_CREATE: "WARRANTY_CREATE",

  // Cash drawer
  CASH_DRAWER_VIEW: "CASH_DRAWER_VIEW",
  CASH_DRAWER_OPEN: "CASH_DRAWER_OPEN",
  CASH_DRAWER_CLOSE: "CASH_DRAWER_CLOSE",
  CASH_DRAWER_RECORD_MOVEMENT: "CASH_DRAWER_RECORD_MOVEMENT",

  // Inventory
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_CREATE: "INVENTORY_CREATE",
  INVENTORY_EDIT: "INVENTORY_EDIT",
  INVENTORY_REORDER_VIEW: "INVENTORY_REORDER_VIEW",
  INVENTORY_HISTORY_VIEW: "INVENTORY_HISTORY_VIEW",
  INVENTORY_ADJUST: "INVENTORY_ADJUST",

  // Suppliers
  SUPPLIERS_VIEW: "SUPPLIERS_VIEW",
  SUPPLIERS_CREATE: "SUPPLIERS_CREATE",
  SUPPLIERS_EDIT: "SUPPLIERS_EDIT",

  // Customers
  CUSTOMERS_VIEW: "CUSTOMERS_VIEW",
  CUSTOMERS_CREATE: "CUSTOMERS_CREATE",
  CUSTOMERS_EDIT: "CUSTOMERS_EDIT",

  // Repairs
  REPAIRS_VIEW: "REPAIRS_VIEW",
  REPAIRS_CREATE: "REPAIRS_CREATE",
  REPAIRS_EDIT: "REPAIRS_EDIT",

  // Reports
  REPORTS_VIEW: "REPORTS_VIEW",

  // Delivery notes
  DELIVERY_NOTES_VIEW: "DELIVERY_NOTES_VIEW",
  DELIVERY_NOTES_CREATE: "DELIVERY_NOTES_CREATE",

  // Inter-store
  INTERSTORE_VIEW: "INTERSTORE_VIEW",
  INTERSTORE_CREATE: "INTERSTORE_CREATE",
  INTERSTORE_RECEIVE: "INTERSTORE_RECEIVE",
  INTERSTORE_SELL: "INTERSTORE_SELL",
  INTERSTORE_RETURN: "INTERSTORE_RETURN",
  INTERSTORE_PAY: "INTERSTORE_PAY",
  INTERSTORE_PAYMENT_ADD: "INTERSTORE_PAYMENT_ADD",
  INTERSTORE_AUDIT_VIEW: "INTERSTORE_AUDIT_VIEW",
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS = {
  OWNER: new Set(ALL_PERMISSIONS),

  MANAGER: new Set([
    PERMISSIONS.DASHBOARD_VIEW,

    // Manager may view settings and role policy, but cannot mutate owner-grade settings.
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_VIEW_ROLES,

    // Manager may see branches, but cannot create/edit/archive branches.
    PERMISSIONS.BRANCHES_VIEW,

    // Manager may view staff, but cannot create/edit/deactivate/reset passwords.
    PERMISSIONS.MEMBERS_VIEW,

    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_VIEW_SALES,
    PERMISSIONS.POS_VIEW_CREDIT,
    PERMISSIONS.SALE_PAYMENT_ADD,
    PERMISSIONS.SALE_CANCEL,
    PERMISSIONS.SALE_REFUND,
    PERMISSIONS.WARRANTY_CREATE,

    PERMISSIONS.CASH_DRAWER_VIEW,
    PERMISSIONS.CASH_DRAWER_OPEN,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.CASH_DRAWER_RECORD_MOVEMENT,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_EDIT,
    PERMISSIONS.INVENTORY_REORDER_VIEW,
    PERMISSIONS.INVENTORY_HISTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,

    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_CREATE,
    PERMISSIONS.SUPPLIERS_EDIT,

    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,

    PERMISSIONS.REPAIRS_VIEW,
    PERMISSIONS.REPAIRS_CREATE,
    PERMISSIONS.REPAIRS_EDIT,

    PERMISSIONS.REPORTS_VIEW,

    PERMISSIONS.DELIVERY_NOTES_VIEW,
    PERMISSIONS.DELIVERY_NOTES_CREATE,

    PERMISSIONS.INTERSTORE_VIEW,
    PERMISSIONS.INTERSTORE_CREATE,
    PERMISSIONS.INTERSTORE_RECEIVE,
    PERMISSIONS.INTERSTORE_SELL,
    PERMISSIONS.INTERSTORE_RETURN,
    PERMISSIONS.INTERSTORE_PAY,
    PERMISSIONS.INTERSTORE_PAYMENT_ADD,
    PERMISSIONS.INTERSTORE_AUDIT_VIEW,
  ]),

  CASHIER: new Set([
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_VIEW_SALES,
    PERMISSIONS.POS_VIEW_CREDIT,
    PERMISSIONS.SALE_PAYMENT_ADD,
    PERMISSIONS.WARRANTY_CREATE,

    PERMISSIONS.CASH_DRAWER_VIEW,
    PERMISSIONS.CASH_DRAWER_OPEN,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.CASH_DRAWER_RECORD_MOVEMENT,

    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,

    PERMISSIONS.DELIVERY_NOTES_VIEW,
    PERMISSIONS.DELIVERY_NOTES_CREATE,

    PERMISSIONS.INTERSTORE_VIEW,
    PERMISSIONS.INTERSTORE_CREATE,
    PERMISSIONS.INTERSTORE_RECEIVE,
    PERMISSIONS.INTERSTORE_SELL,
    PERMISSIONS.INTERSTORE_RETURN,
    PERMISSIONS.INTERSTORE_PAYMENT_ADD,
  ]),

  SELLER: new Set([
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.POS_VIEW_SALES,

    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,

    PERMISSIONS.INTERSTORE_VIEW,
    PERMISSIONS.INTERSTORE_SELL,
  ]),

  STOREKEEPER: new Set([
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_REORDER_VIEW,
    PERMISSIONS.INVENTORY_HISTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,

    PERMISSIONS.SUPPLIERS_VIEW,

    PERMISSIONS.DELIVERY_NOTES_VIEW,

    PERMISSIONS.INTERSTORE_VIEW,
    PERMISSIONS.INTERSTORE_RECEIVE,
    PERMISSIONS.INTERSTORE_RETURN,
  ]),

  TECHNICIAN: new Set([
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.REPAIRS_VIEW,
    PERMISSIONS.REPAIRS_CREATE,
    PERMISSIONS.REPAIRS_EDIT,

    PERMISSIONS.CUSTOMERS_VIEW,

    PERMISSIONS.INTERSTORE_VIEW,
  ]),

  PLATFORM_ADMIN: new Set(ALL_PERMISSIONS),
};

function normalizeRole(role) {
  return String(role || "").trim().toUpperCase();
}

function roleHas(role, permission) {
  const set = ROLE_PERMISSIONS[normalizeRole(role)];
  return Boolean(set && set.has(permission));
}

function listRolePermissions(role) {
  const set = ROLE_PERMISSIONS[normalizeRole(role)];
  return set ? Array.from(set) : [];
}

function exportRolePermissions() {
  return Object.fromEntries(
    Object.entries(ROLE_PERMISSIONS).map(([role, set]) => [role, Array.from(set)])
  );
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  roleHas,
  listRolePermissions,
  exportRolePermissions,
};