const WHATSAPP_WORKSPACE_ROLES = [
  "OWNER",
  "MANAGER",
  "CASHIER",
  "SELLER",
  "STOREKEEPER",
  "TECHNICIAN",
];

const WHATSAPP_ASSIGNABLE_ROLES = [...WHATSAPP_WORKSPACE_ROLES];

module.exports = {
  WHATSAPP_WORKSPACE_ROLES,
  WHATSAPP_ASSIGNABLE_ROLES,
};